from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from app.models import MatchRef, MatchSnapshot


class BaseProvider(ABC):
    """异步数据提供方抽象基类。"""

    name: str = "base"

    def __init__(self, settings: Any) -> None:
        self.settings = settings

    @abstractmethod
    async def get_upcoming_matches(self, date: str | None = None) -> list["MatchRef"]:
        """获取即将开始的比赛列表。"""

    @abstractmethod
    async def get_match_snapshot(self, match_id: str) -> "MatchSnapshot":
        """获取单场比赛的聚合快照。"""

    def is_configured(self) -> bool:
        """默认认为 provider 已配置，子类可按需覆盖。"""
        return True

    def is_enabled(self) -> bool:
        """默认根据 enabled 配置项控制启用状态。"""
        enabled = getattr(self.settings, "enabled", True)
        return bool(enabled) and self.is_configured()

    def build_demo_match(self, match_id: str = "demo-001") -> "MatchRef":
        """构造一条演示比赛数据。"""
        from app.models import MatchRef, TeamRef

        return MatchRef(
            id=match_id,
            league="Demo League",
            kickoff="2026-01-01T12:00:00Z",
            home_team=TeamRef(id="demo-home", name="Demo FC", short_name="DFC"),
            away_team=TeamRef(id="demo-away", name="Example United", short_name="EXU"),
            status="SCHEDULED",
            venue="Demo Stadium",
        )

    def build_demo_snapshot(self, match_id: str = "demo-001") -> "MatchSnapshot":
        """构造一条演示比赛快照数据。"""
        from app.models import InjuryNote, MatchSnapshot, OddsPrice, OddsSnapshot, TeamForm

        return MatchSnapshot(
            match=self.build_demo_match(match_id=match_id),
            home_form=TeamForm(
                last_5=["W", "D", "W", "L", "W"],
                points_per_match=2.0,
                goals_for_avg=1.8,
                goals_against_avg=0.8,
            ),
            away_form=TeamForm(
                last_5=["L", "D", "W", "L", "D"],
                points_per_match=0.8,
                goals_for_avg=0.9,
                goals_against_avg=1.6,
            ),
            injuries=[
                InjuryNote(team="Demo FC", player="Demo Striker", status="doubtful", impact="medium"),
                InjuryNote(team="Example United", player="Example Defender", status="out", impact="high"),
            ],
            weather="clear, 22C",
            pre_match_notes=[
                "Demo data generated by provider base class.",
                f"Snapshot source: {self.name}",
            ],
            odds=OddsSnapshot(
                match_id=match_id,
                source=self.name,
                last_update="2026-01-01T10:00:00Z",
                prices=[
                    OddsPrice(bookmaker="demo-book", market="1X2", selection="home", price=1.95),
                    OddsPrice(bookmaker="demo-book", market="1X2", selection="draw", price=3.40),
                    OddsPrice(bookmaker="demo-book", market="1X2", selection="away", price=4.10),
                ],
            ),
            provider_evidence=[
                f"provider={self.name}",
                "demo_mode=true",
            ],
        )

    def _safe_float(self, value: Any, default: float = 0.0) -> float:
        """安全地将输入转换为浮点数。"""
        try:
            if value is None or value == "":
                return default
            return float(value)
        except (TypeError, ValueError):
            return default
